# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Reid | Senior Software Developer
email: matt@matt-reid.co.uk
description: >
  Matthew Reid is a software developer and web developer, specialising in Java, Node and Scala as well as html js and css.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.matt-reid.co.uk" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Matt Reid'
bio: >
  Mea suas vituperatoribus et, virtute corpora quaestio cum ut.
  Ne solet nostrum complectitur pri, vis ut inani populo.
author_image: "/assets/images/author.jpg"
twitter_username: Matthew_Reid
github_username:  drei01

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
