# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Reid | Senior Software Developer
email: matt@matt-reid.co.uk
description: >
    Matthew Reid is a Full Stack web developer, specialising in Java and the JVM, js and web frameworks. He has a passion for clean code, entrepreneurship, company culture and making the world a better place.
logo: '/assets/images/favicon.ico'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://www.matt-reid.co.uk' # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

name: 'Matt Reid'
bio: >
    Lead Software Architect. Java, Node.js and TypeScript enthusiast.
author_image: '/assets/images/matt-reid.jpg'
twitter_username: Matthew_Reid
github_username: drei01

# Build settings
markdown: kramdown

kramdown:
    parse_block_html: true

plugins:
    - jekyll-paginate
    - jekyll-sitemap
