# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# change the followings to match your Github username and repo name
baseurl: "/ " # the name of your github repo
url: "https://www.matt-reid.co.uk" # the url of your github pages

# site information used in page title, meta data etc.
title: "Matt Reid | Senior Software Developer"
description:  >
    Matthew Reid is a Full Stack web developer, specialising in Java and the JVM, js and web frameworks. He has a passion for clean code, entrepreneurship, company culture and making the world a better place.

# color theme for links
theme-color: pink # indigo|yellow|pink|green|stone|

# homepage information
author: 'Matt Reid'
author-bio: >
    Solo Entrepreneur | Lead Software Architect
author-image: '/assets/images/matt-reid.png'

# navigation menu
show-nav-menu: true

nav-menu:
- text: Home
  permalink: 
- text: About
  permalink: about

# use false to turn off any social media links
twitter: https://twitter.com/Matthew_Reid
facebook: false
instagram: false
github: https://github.com/drei01
linkedin: false
medium: false
google-scholar: false
email: mailto:matt@matt-reid.co.uk

# footer information
footer-msg: "All content copyright Matthew Reid • All rights reserved."
footer-msg-link: "https://www.pricewell.com"

# Site settings
logo: '/assets/images/favicon.ico'
baseurl: '' # the subpath of your site, e.g. /blog
paginate: 5 # The number of posts to show per page on your homepage

# Build settings
markdown: kramdown

kramdown:
    parse_block_html: true

plugins:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-paginate
